// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHCRSi74l43LuFiWnAXsibgf00CePjB88',
    appId: '1:405847243905:web:e0b03790dcd7f9517fa180',
    messagingSenderId: '405847243905',
    projectId: 'daksh-ptype',
    authDomain: 'daksh-ptype.firebaseapp.com',
    storageBucket: 'daksh-ptype.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3NDMWoEnGwRKpfXKrYidFM1nkwSoIkKM',
    appId: '1:405847243905:ios:c676914e09f4efda7fa180',
    messagingSenderId: '405847243905',
    projectId: 'daksh-ptype',
    storageBucket: 'daksh-ptype.appspot.com',
    iosBundleId: 'com.example.dakshPtype',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJa-piNgCPkwXhs-YWV-IJYpAgmTctGMY',
    appId: '1:405847243905:android:3df355b0c747283d7fa180',
    messagingSenderId: '405847243905',
    projectId: 'daksh-ptype',
    storageBucket: 'daksh-ptype.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHCRSi74l43LuFiWnAXsibgf00CePjB88',
    appId: '1:405847243905:web:805ff2127f5165fd7fa180',
    messagingSenderId: '405847243905',
    projectId: 'daksh-ptype',
    authDomain: 'daksh-ptype.firebaseapp.com',
    storageBucket: 'daksh-ptype.appspot.com',
  );

}